[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
MyModule = '0x4e0a394db2ded351d94aff3c25c6fe41ab85cdee05d232629660f41427c311eb'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "testnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]